#!/bin/bash
# Git & GitHub 设置脚本

echo "======================================"
echo "Git 仓库已初始化！"
echo "======================================"
echo ""
echo "当前状态："
git status
echo ""
echo "======================================"
echo "下一步：创建 GitHub 仓库"
echo "======================================"
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 在浏览器中访问 GitHub 创建新仓库："
echo "   https://github.com/new"
echo ""
echo "2. 仓库名称建议："
echo "   - forgery-detection-competition"
echo "   - image-forgery-detection"
echo "   - competition-1"
echo ""
echo "3. 创建仓库后，运行以下命令连接："
echo ""
echo "   git remote add origin https://github.com/<你的用户名>/<仓库名>.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "4. 或者使用 SSH（如果已配置）："
echo ""
echo "   git remote add origin git@github.com:<你的用户名>/<仓库名>.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "======================================"
echo "当前 Git 配置："
echo "======================================"
git config --list | grep -E "(user\.|remote\.)"
echo ""
echo "✅ Git 仓库已准备好首次提交！"
